<h2 class="h2 text-center my-2">Вход</h2>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-3">
            <form action="login" method="post">
                <!-- csrf -->
                <input type="hidden" name="token" value="<?=$_COOKIE['PHPSESSID'] ?? null;?>">

                <div class="form-floating mb-3">
                    <label for="login">Логин</label>
                    <input type="text" class="form-control" id="login" name="login" value="<?=$_SESSION['loginInput'] ?? null ?>">
                </div>

                <div class="form-floating">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>

                <button type="submit" class="btn btn-success mt-3">Войти</button>
            </form>
        </div>
    </div>
</div>