<h2 class="h2 text-center my-2"><?=$title;?></h2>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-3">
            <form action="register" method="post">
                <!-- csrf -->
                <input type="hidden" name="token" value="<?=$_COOKIE['PHPSESSID'];?>">
                
                <div class="form-group">
                    <label for="">Email:</label>
                    <input class="form-control mb-3" type="email" name="email">
                </div>
                <div class="form-group">
                    <label for="">Логин:</label>
                    <input class="form-control mb-3" type="text" name="login">
                </div>
                <div class="form-group">
                    <label for="">Пароль:</label>
                    <input class="form-control mb-3" type="password" name="password">
                </div>
                <div class="form-group">
                    <label for="">Повторите пароль:</label>
                    <input class="form-control mb-3" type="password" name="password_repeat">
                </div>
                <button type="submit" class="btn btn-success">Регистрация</button>
            </form>
        </div>
    </div>
</div>