<?php
use App\models\Account;
?>
<div class="container">
    <div class="row">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Проект SF-27. Auth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/">Главная</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="secret">Secret</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="list">Список</a>
                        </li>
                        
                        <?php if (Account::checkAuth()) : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="logout">Выход</a>
                        </li>

                        <?php elseif (!Account::checkAuth()) : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="register">Регистрация</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="register_google">Авторизация Google</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="login">Вход</a>
                        </li>
                        <?php endif; ?>
                        
                    </ul>

                </div>
            </div>
        </nav>

    </div>
</div>